[project]
id = "your-image-pro-ai-toolkit"

[build]
builder = "gcr.io/buildpacks/builder"

[[build.buildpacks]]
id = "google.nodejs.npm"
version = "1.1.0"

[[build.env]]
name = "NPM_BUILD_SCRIPT"
value = "build"

[[build.env]]
name = "NPM_START_SCRIPT"
value = "start"
